name: Actions Workflow

on: [push]

jobs: 
    run-github-actions:
      runs-on: ubuntu-latest
      steps: 
        - name: List Files
          run: |
            pwd
            ls
        - name: Checkout
          uses: actions/checkout@v1
        - name: Simple JS Action
          id: greet
          uses: actions/hello-world-javascript-action@master
          with: 
            who-to-greet: Sagar
        - name: Log Greeting T ime
          run: echo "${{ steps.greet.outputs.time }}"